# Generated by Django 5.2.7 on 2025-10-10 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_remove_project_budget_project_deadline_project_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='deadline',
        ),
    ]
