# Generated by Django 5.2.7 on 2025-10-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_project_skills_alter_project_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='skills',
            field=models.CharField(default=1, max_length=200, null=True),
        ),
    ]
