# Generated by Django 5.2.7 on 2025-10-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_alter_project_description_alter_project_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientHire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('project_title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('budget_range', models.CharField(choices=[('5k-10k', '₹5,000 - ₹10,000'), ('10k-25k', '₹10,000 - ₹25,000'), ('25k-50k', '₹25,000 - ₹50,000'), ('50k+', '₹50,000+ (Custom Quote)')], max_length=10)),
                ('required_duration', models.CharField(choices=[('1W', 'Less than 1 Week'), ('2W', '1 - 2 Weeks'), ('1M', '2 Weeks - 1 Month'), ('1-3M', '1 - 3 Months'), ('3-6M', '3 - 6 Months'), ('6M+', 'Ongoing / Long Term')], max_length=10)),
                ('language', models.CharField(blank=True, help_text='Optional: Specific programming language or technology required (e.g., Python, React, Figma).', max_length=100, null=True)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
