# Generated by Django 5.2.7 on 2025-10-13 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_skill_alter_customuser_skills_freelancer'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='experience_years',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='portfolio_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
